const papers=[
 {id:'wbi11-2601',title:'January 2026 — Unit 1',code:'WBI11/01',date:'9 Jan 2026',time:'1h 30m',marks:80,qp:'biology-u1-jan26-qp.pdf',ms:'biology-u1-jan26-ms.pdf'},
 {id:'wbi11a-2601',title:'January 2026 — Unit 1 (01A)',code:'WBI11/01A',date:'9 Jan 2026',time:'1h 30m',marks:80,qp:'biology-u1a-jan26-qp.pdf',ms:'biology-u1a-jan26-ms.pdf'}
];
const qs=[
 {n:'1',marks:5,q:'Complete the description of how substances move through the cell membrane.',scheme:[
  ['phospholipids / phospholipid bilayer / hydrophobic or non-polar fatty acid tails',['phospholipid','bilayer','hydrophobic','non-polar','fatty acid tails']],['facilitated diffusion',['facilitated diffusion']],['active transport',['active transport']],['ATP / carrier proteins / protein pumps / energy',['atp','carrier protein','protein pump','energy']],['endocytosis',['endocytosis']]
 ],note:'Five independent marking points. “Diffusion” alone is not accepted for facilitated diffusion.'},
 {n:'2(a)(i)',marks:1,q:'Whose law can be used to calculate the rate of diffusion?',type:'mcq',options:['A — Benedict’s','B — Fick’s','C — Meselson’s','D — Stahl’s'],correct:'B'},
 {n:'2(a)(ii)',marks:3,q:'Explain how the rate of diffusion through gas exchange surfaces is affected by cystic fibrosis.',scheme:[['thick / sticky mucus is produced',['thick mucus','sticky mucus']],['mucus blocks / narrows / remains in the airways or alveoli',['block','narrow','airway','alveoli','bronchi','bronchiole','trachea']],['reduced oxygen / carbon dioxide concentration gradient',['concentration gradient','oxygen','carbon dioxide']],['reduced rate of diffusion / gas exchange',['rate of diffusion','gas exchange','diffusion']]],cap:3,note:'Award any three. Increased diffusion distance/thicker alveolar walls or reduced alveolar surface area may also be creditworthy.'},
 {n:'2(b)',marks:3,q:'Describe how one named method of prenatal testing can be used to detect cystic fibrosis.',groups:[[['amniocentesis',['amniocentesis']],['amniotic fluid / cells from amniotic fluid',['amniotic fluid','amniotic sac']],['analyse for the CF mutation / faulty allele',['mutation','faulty allele','defective allele']]],[[ 'chorionic villus sampling / CVS',['chorionic villus','cvs']],['placental / chorionic cells or tissue',['placenta','chorion','chorionic villi']],['analyse for the CF mutation / faulty allele',['mutation','faulty allele','defective allele']]],[[ 'PUBS / cordocentesis',['pubs','cordocentesis','percutaneous umbilical']],['blood from the umbilical cord',['blood','umbilical cord']],['analyse for the CF mutation / faulty allele',['mutation','faulty allele','defective allele']]]]},
 {n:'3(a)',marks:1,q:'Name one obesity indicator other than BMI.',alts:['skin fold thickness','waist-to-hip ratio','waist circumference','percentage body fat'],keys:['skin fold','waist to hip','waist-to-hip','waist circumference','waist measurement','percentage body fat']},
 {n:'3(b)(i)',marks:1,q:'Determine the weight category of a person who is 160 cm tall with body mass of 76 kg.',alts:['overweight'],keys:['overweight']},
 {n:'3(b)(ii)',marks:3,q:'Explain how a person with a BMI of 25.2 could change their diet to reduce their risk of coronary heart disease.',scheme:[['reduce cholesterol / saturated fat intake and link this to reduced atheroma formation',['saturated fat','cholesterol','atheroma','plaque','atherosclerosis']],['reduce salt intake and link this to blood pressure / endothelial damage',['salt','blood pressure','endothelial']],['increase antioxidants and link to reduced free radicals',['antioxidant','free radical']],['increase fibre / roughage and link to reduced cholesterol absorption',['fibre','roughage','cholesterol absorption']],['slightly reduce calories / sugar / fat because the person is only slightly overweight',['calorie','sugar','portion','slightly overweight']]],cap:3},
 {n:'4(a)(i)',marks:2,q:'Complete the fruit-fly genotype/phenotype table for eye colour and sex.',scheme:[['all eye colours correctly identified across the genotypes',['red','white']],['all sexes correctly identified across the genotypes',['female','male']]],note:'The official table awards one mark for all colours correct and one for all sexes correct.'},
 {n:'4(a)(ii)',marks:1,q:'In a population of 2000 fruit flies, the ratio of red eyes to white eyes was 4:1. How many had red eyes?',type:'mcq',options:['A — 400','B — 500','C — 1500','D — 1600'],correct:'D'},
 {n:'4(b)',marks:3,q:'Compare and contrast the types of sex chromosomes found in female and male Komodo dragons with those found in humans.',scheme:[['both species have two different types of sex chromosome',['different','sex chromosome']],['both have one sex with two of the same chromosomes and one sex with different chromosomes',['same','different','chromosome']],['Komodo males have identical chromosomes whereas human females have identical chromosomes (or equivalent comparison)',['komodo','male','identical','human','female']]]},
 {n:'5(a)',marks:1,q:'State the meaning of the term risk factor.',scheme:[['a factor / characteristic that increases the likelihood or probability of an event, disease or condition',['factor','characteristic','likelihood','probability','chance','disease','condition']]]},
 {n:'5(b)',marks:1,q:'Which are non-lifestyle risk factors associated with coronary heart disease?',type:'mcq',options:['A — age and diet high in cholesterol','B — age and sex','C — inactivity and diet high in cholesterol','D — sex and inactivity'],correct:'B'},
 {n:'5(c)',marks:2,q:'Describe the relationship between the number of cigarettes smoked per day and the relative risk of CHD.',scheme:[['overall, more cigarettes smoked is associated with greater relative risk of CHD',['increase','positive correlation','greater risk']],['the relationship is non-linear',['non-linear','nonlinear']],['there is a relative risk of CHD even with no smoking',['no smoking','zero cigarettes','without smoking']]],cap:2},
 {n:'5(d)(i)',marks:1,q:'A person smoked 5 cigarettes a day for 12 years. Calculate the mean number of cigarettes smoked per year, using 365.25 days per year.',alts:['1826','1,826'],keys:['1826','1,826']},
 {n:'5(d)(ii)',marks:3,q:'Explain why this person’s perception of their risk of CHD is likely to be different from their actual risk.',scheme:[['may underestimate / misreport / not know the number of cigarettes smoked',['underestimate','under-estimate','lie','not know','misreport']],['may not smoke the same number every day',['same number','each day','every day','not everyday']],['may not know exactly how long they have smoked',['how long','years','duration']],['may not realise how important smoking is as a risk factor',['not realise','risk factor','awareness','education']]],cap:3},
 {n:'6(a)',marks:2,q:'Draw a triglyceride using the glycerol, fatty-acid and ester-bond shapes shown in the paper.',scheme:[['one glycerol, three fatty acids and three bonds are shown',['glycerol','three fatty','3 fatty','three bonds','3 bonds']],['all components are joined together correctly',['joined','attached','ester']]],note:'This is a drawing question. For the most accurate marking, describe your diagram in words or compare it with the original mark scheme.'},
 {n:'6(b)',marks:1,q:'Which row is correct for a saturated fatty acid?',type:'mcq',options:['A','B','C','D'],correct:'A'},
 {n:'6(c)(i)',marks:1,q:'Estimate the melting point of a saturated fatty acid with a chain length of ten carbons.',scheme:[['a whole-number estimate between 15 °C and 50 °C',['15','20','25','30','35','40','45','50']]]},
 {n:'6(c)(ii)',marks:4,q:'Comment on the relationships between fatty-acid melting point and carbon number, presence/absence of C=C bonds, and number of C=C bonds.',scheme:[['for saturated fatty acids, melting point increases as chain length / carbon number increases',['chain length','carbon','increase']],['the saturated fatty acids shown are liquid above the relevant temperature threshold',['saturated','liquid']],['no clear relationship between chain length and melting point for the unsaturated fatty acids shown',['unsaturated','no relationship','no correlation']],['saturated fatty acids have higher melting points than unsaturated fatty acids',['saturated','higher','unsaturated']],['melting point decreases as the number of C=C double bonds increases',['double bond','decrease']]],cap:4},
 {n:'6(c)(iii)',marks:1,q:'Which row correctly assigns the melting points 3 °C, −6 °C and −10 °C to canola, peanut and sesame oils?',type:'mcq',options:['A','B','C','D'],correct:'C'},
 {n:'7(a)(i)',marks:1,q:'Which are the products when lactose is digested?',type:'mcq',options:['A — fructose and sucrose','B — galactose and glucose','C — galactose and sucrose','D — glucose and fructose'],correct:'B'},
 {n:'7(a)(ii)',marks:2,q:'Explain why lactase speeds up the rate of digestion of lactose.',scheme:[['lactase / enzymes act as catalysts',['catalyst','catalyse']],['lactase lowers the activation energy',['activation energy']],['this enables glycosidic bonds between glucose and galactose to be broken',['glycosidic','glucose','galactose']]],cap:2},
 {n:'7(b)',marks:1,q:'68% of a world population of 8.1 × 10⁹ people were lactose intolerant. How many people is this, to two significant figures?',type:'mcq',options:['A — 2.59 × 10⁹','B — 2.6 × 10⁹','C — 5.5 × 10⁹','D — 5.51 × 10⁹'],correct:'C'},
 {n:'7(c)',marks:6,q:'Explain why lactase activity changes when it is trapped in alginate beads. Use the pH and temperature graphs in the paper.',level:true,scheme:[['use relevant comparisons from the pH graph, including range/optimum/activity',['ph','optimum','range']],['explain pH effects using H⁺ concentration, R-group ionisation, bonds and active-site shape',['hydrogen ion','r group','bond','active site']],['explain how alginate can stabilise/protect enzyme structure at different pH values',['alginate','stabilise','protect','shape']],['use relevant comparisons from the temperature graph, including optimum/activity',['temperature','optimum']],['explain temperature effects using kinetic energy/collisions and denaturation/R-group vibration',['kinetic energy','collision','denature','vibrate']],['explain how alginate can stabilise the active site / reduce R-group movement at higher temperatures',['alginate','active site','stabilise','movement']]],note:'This is a 6-mark level-of-response question. The AI examiner should judge scientific reasoning, use of both graphs and logical structure, not simply count keywords.'},
 {n:'8(a)(i)',marks:2,q:'Describe two conclusions from the graph showing percentage of living cancer cells after treatment with different concentrations of Sch B.',scheme:[['increasing Sch B concentration decreases the percentage/number of living cancer cells',['increase','concentration','decrease','living cancer']],['an effect is seen only above the lowest concentrations / minimum effective concentration is around 6.25 μmol dm⁻³',['6.25','minimum','effect']],['even the highest concentration does not destroy all cancer cells',['highest','not all','cancer cells']]],cap:2},
 {n:'8(a)(ii)',marks:1,q:'State why DNA synthesis was used to assess the ability of cancer cells to divide.',scheme:[['DNA must be replicated / synthesised before cell division or mitosis',['dna','replicated','replication','synthesis','cell division','mitosis']]]},
 {n:'8(b)(i)',marks:1,q:'Each mouse received 200 μl of a cell suspension at 1 × 10⁷ cells per cm³. Calculate the number of cells injected.',alts:['2 × 10^6','2x10^6','2000000','2,000,000','2 million'],keys:['2 × 10','2x10','2000000','2,000,000','2 million']},
 {n:'8(b)(ii)',marks:1,q:'Suggest what the control group of mice was treated with.',scheme:[['the solvent/liquid used to dissolve the drug, e.g. water or saline',['solvent','water','saline','salt solution','liquid']]]},
 {n:'8(b)(iii)',marks:2,q:'Calculate the actual volume of the tumour from the Sch B-treated mouse using the formula and dimensions in the paper.',scheme:[['correct volume calculation / working using the stated formula',['volume','π','pi','10']],['final value in the accepted range, approximately 600–681 mm³',['600','628','630','650','680','681']]],note:'The official scheme accepts several values because the longest diameter is measured from the printed image.'},
 {n:'8(b)(iv)',marks:2,q:'Explain why the tumour-volume formula may not give accurate values.',scheme:[['tumours are not uniform / regular in shape',['not uniform','irregular','not regular']],['the measured width/length depends on where the measurement is taken',['where','measurement','width','length']],['the ruler/equipment measures only to limited precision in mm',['ruler','mm','precision']],['the formula may not be appropriate for the tumour shape',['formula','appropriate','shape']]],cap:2},
 {n:'8(c)(i)',marks:4,q:'Explain how a DNA mutation can result in glycine being replaced by aspartate in the polypeptide.',scheme:[['the DNA mutation is a substitution',['substitution']],['the change is transcribed/copied into mRNA',['mrna','transcription','copied']],['the altered codon/triplet codes for aspartate',['codon','triplet','aspartate']],['a tRNA carrying aspartate binds to the altered codon',['trna','aspartate','anticodon']],['aspartate is joined into the polypeptide by peptide bonds',['peptide bond','polypeptide','aspartate']]],cap:4},
 {n:'8(c)(ii)',marks:2,q:'Suggest why it is difficult to develop drugs that target only the polypeptide synthesised from the gene with the G12D mutation.',scheme:[['the target site is only one amino acid / aspartate',['one amino acid','aspartate']],['the drug may fail to bind specifically to that aspartate',['bind','aspartate','specific']],['other proteins also contain aspartate',['other proteins','aspartate']],['therefore the drug could affect other proteins',['affect other proteins','other proteins']]],cap:2},
 {n:'9(a)',marks:6,q:'Explain how development of a DVT in the leg can result in death from a pulmonary embolism. Use the diagram and your knowledge of clotting and circulation.',level:true,scheme:[['formation of the leg clot: impaired venous return while sitting, reduced skeletal-muscle pump and blood pooling around valves',['sitting','skeletal muscle','valve','blood flow']],['blood-clotting pathway: platelets/thromboplastin → prothrombin/thrombin → fibrinogen/fibrin → trapped cells',['platelet','thromboplastin','thrombin','prothrombin','fibrin','fibrinogen']],['part of the clot breaks away and travels through veins/vena cava/right side of heart to the pulmonary artery',['breaks','vena cava','right atrium','right ventricle','pulmonary artery']],['embolus blocks pulmonary blood flow so deoxygenated blood cannot reach the lungs for oxygenation',['block','pulmonary','lungs','oxygen']],['reduced oxygen delivery prevents sufficient aerobic respiration/ATP and can cause fatal organ damage',['oxygenated','aerobic respiration','energy','atp','death']]],note:'This is a 6-mark level-of-response question. The official scheme rewards linked explanations across multiple aspects rather than isolated facts.'},
 {n:'9(b)(i)',marks:2,q:'Explain why people taking anticoagulants must monitor their blood clotting time.',scheme:[['if dose is too high, clotting time is too long / blood clots too slowly',['too high','too long','slow']],['this can cause excessive or uncontrolled blood loss / haemorrhage',['blood loss','bleeding','haemorrhage']],['if dose is too low, clotting time is too short / blood clots too quickly',['too low','too short','fast']],['this raises risk of DVT, embolism, stroke or heart attack',['dvt','embolism','stroke','heart attack']]],cap:2},
 {n:'9(b)(ii)',marks:2,q:'Explain why the copper particles will almost stop moving as the blood clots.',scheme:[['the blood/clot becomes thicker, sticky or forms a fibrin mesh',['thicker','sticky','fibrin','mesh']],['this creates resistance or traps the copper particles so they cannot move freely',['resistance','trapped','stuck','movement']]]},
 {n:'9(b)(iii)',marks:1,q:'Determine the blood clotting time in the smartphone recording using the end time shown on the graph.',alts:['19 seconds','19 s','19','19.0'],keys:['19']},
 {n:'9(b)(iv)',marks:2,q:'Suggest why an end time halfway between points A and B was used to determine blood clotting time.',scheme:[['the particles do not all stop moving at exactly the same time / there is no clear single endpoint',['not all','same time','no clear','end point','endpoint']],['there is a large/rapid change in particle movement before movement almost stops',['rapid','large change','decrease','movement']],['the halfway point provides a representative middle/average endpoint',['halfway','midpoint','middle','average','mean','median']]],cap:2},
 {n:'9(b)(v)',marks:2,q:'Comment on the blood clotting times measured using the smartphone and conventional methods.',scheme:[['there is a positive correlation / the two methods give comparable trends',['positive correlation','both increase','comparable']],['the methods do not give exactly the same clotting times',['not same','difference','do not give']],['at lower clotting times the smartphone method records higher values',['lower','smartphone','higher']],['at higher clotting times the smartphone method records lower values',['higher','smartphone','lower']]],cap:2}
];
let state={view:'papers',paper:null,qi:0,answers:{},results:{}}; const app=document.querySelector('#app');
function go(v){state.view=v;render()} function openPaper(id){state.paper=papers.find(p=>p.id===id);state.view='questions';render()} function openQ(i){state.qi=i;state.view='viewer';render()}
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function aiKey(){return sessionStorage.getItem('examTutorOpenRouterKey')||''}
function saveAiKey(){let el=document.querySelector('#aiKey');let v=(el?.value||'').trim();if(!v)return alert('Paste your OpenRouter API key first.');sessionStorage.setItem('examTutorOpenRouterKey',v);render()}
function removeAiKey(){sessionStorage.removeItem('examTutorOpenRouterKey');render()}
function setupAI(){let existing=aiKey();return `<div class="ai-setup"><b>AI examiner setup</b><p class="ai-note">Connect an OpenRouter key to turn on semantic AI marking. The key is kept only in this browser tab/session in this prototype and is not included in the downloaded project.</p><input id="aiKey" type="password" autocomplete="off" placeholder="OpenRouter API key" value="${esc(existing)}"><button class="secondary" onclick="saveAiKey()">${existing?'Update key':'Connect AI'}</button>${existing?` <button class="danger-link" onclick="removeAiKey()">Disconnect</button>`:''}</div>`}
function schemeText(q){if(q.type==='mcq')return `Correct option: ${q.correct}.`;if(q.groups)return q.groups.map((g,i)=>`Accepted route ${i+1}: ${g.map(x=>x[0]).join(' | ')}`).join('\n');if(q.alts)return `Accept one of: ${q.alts.join('; ')}`;return (q.scheme||[]).map((x,i)=>`${i+1}. ${x[0]}`).join('\n')+(q.cap?`\nMaximum ${q.cap} marks.`:'')+(q.note?`\nExaminer guidance: ${q.note}`:'')}
function parseAIJson(raw){let t=String(raw||'').trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();let a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)t=t.slice(a,b+1);return JSON.parse(t)}
async function aiMark(){let p=state.paper,q=qs[state.qi],key=p.id+'-'+state.qi,a=getAnswer(q,key);if(!a)return alert('Write or select an answer first.');let token=aiKey();if(!token)return alert('Connect your OpenRouter key in AI examiner setup first.');state.answers[key]=a;let btn=document.querySelector('#aiMarkBtn');if(btn){btn.disabled=true;btn.textContent='AI examiner is marking…'}
 const system=`You are a strict Pearson Edexcel International A Level Biology examiner. Mark only from the supplied question-specific marking guidance. Do not award a point merely because a related keyword appears: the student's statement must communicate the required scientific idea. Respect the maximum mark. Do not invent extra requirements. Return ONLY valid JSON with keys score (integer), max_score (integer), awarded (array of short strings), missed (array of short strings), feedback (short string), improved_answer (concise exam-style answer).`;
 const user=`Question ${q.n} (${q.marks} marks):\n${q.q}\n\nOfficial marking guidance:\n${schemeText(q)}\n\nStudent answer:\n${a}`;
 try{let cfg=window.EXAM_TUTOR_AI||{};let res=await fetch(cfg.endpoint||'https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json','X-Title':'Private Exam Tutor'},body:JSON.stringify({model:cfg.model||'openrouter/free',temperature:0,messages:[{role:'system',content:system},{role:'user',content:user}]})});let data=await res.json();if(!res.ok)throw new Error(data?.error?.message||`API error ${res.status}`);let raw=data?.choices?.[0]?.message?.content;if(!raw)throw new Error('The AI returned an empty response.');let j=parseAIJson(raw);let score=Math.max(0,Math.min(q.marks,Number(j.score)||0));state.results[key]={score,details:[...(j.awarded||[]).map(x=>({ok:true,text:x})),...(j.missed||[]).map(x=>({ok:false,text:x}))],answer:a,ai:true,feedback:j.feedback||'',improved:j.improved_answer||''};render()}catch(e){alert('AI marking could not run: '+e.message+'\n\nYour answer has been kept. You can retry or use the local marker.');render()}}
function render(){ if(state.view==='papers') papersView(); else if(state.view==='questions') questionList(); else viewer(); }
function papersView(){app.innerHTML=`<div class="hero"><div><span class="eyebrow">YOUR STUDY STACKS</span><h1>What do you want to practise?</h1><p>Exam questions, instant marking and feedback from the official Pearson mark scheme.</p></div><div class="stat"><b>2</b><span>active stacks</span></div></div><div class="sectionTitle"><div><h2>Biology · Unit 1</h2><p>Molecules, Diet, Transport and Health</p></div></div><div class="paperGrid">${papers.map(p=>`<article class="paperCard" onclick="openPaper('${p.id}')"><div class="paperTop"><span class="subjectBadge">BIOLOGY</span><span class="ready">● Ready</span></div><h3>${p.title}</h3><p>${p.code}</p><div class="paperMeta"><span>${p.time}</span><span>${p.marks} marks</span></div><button class="primary">Open stack →</button></article>`).join('')}</div><div class="notice"><b>Marking source:</b> the supplied Pearson mark schemes. All questions from the January 2026 Unit 1 paper are now included. The original PDFs remain available inside each paper.</div>`}
function questionList(){let p=state.paper;app.innerHTML=`<button class="back" onclick="go('papers')">← Papers</button><div class="paperHeader"><div><span class="subjectBadge">BIOLOGY</span><h1>${p.title}</h1><p>${p.code} · ${p.time} · ${p.marks} marks</p></div><div class="pdfBtns"><a href="${p.qp}" target="_blank">Question paper ↗</a><a href="${p.ms}" target="_blank">Mark scheme ↗</a></div></div><div class="questionList">${qs.map((q,i)=>{let r=state.results[p.id+'-'+i];return `<div class="qrow" onclick="openQ(${i})"><div class="qnum">${q.n}</div><div class="grow"><b>${q.q}</b><span>${q.marks} mark${q.marks>1?'s':''}</span></div>${r?`<div class="miniScore">${r.score}/${q.marks}</div>`:''}<div class="chev">›</div></div>`}).join('')}</div>`}
function answerUI(q,key){if(q.type==='mcq')return `<div class="choices">${q.options.map(o=>`<label><input type="radio" name="mcq" value="${o[0]}" ${state.answers[key]===o[0]?'checked':''}> <span>${o}</span></label>`).join('')}</div>`;return `<textarea id="ans" class="answer" placeholder="Write your exam answer here...">${esc(state.answers[key]||'')}</textarea>`}
function viewer(){let p=state.paper,q=qs[state.qi],key=p.id+'-'+state.qi,r=state.results[key];app.innerHTML=`<button class="back" onclick="state.view='questions';render()">← Questions</button><div class="viewer"><section class="exam"><div class="examBar"><span>${p.code}</span><b>${q.marks} MARK${q.marks>1?'S':''}</b></div><div class="qn">Question ${q.n}</div><div class="questionText">${q.q}</div>${answerUI(q,key)}<div class="actions"><button class="primary" id="aiMarkBtn" onclick="aiMark()">✦ Mark with AI</button><button class="secondary" onclick="mark()">Local mark</button><button class="secondary" onclick="clearAns()">Clear</button></div>${r?resultHTML(r,q):''}</section><aside class="sidebar"><div class="sideCard"><span class="tiny">PAPER</span><b>${p.title}</b><p>${p.code}</p></div><div class="sideCard"><span class="tiny">PROGRESS</span><b>${Object.keys(state.results).filter(k=>k.startsWith(p.id)).length} / ${qs.length} parts attempted</b></div><div class="ai-status"><span class="ai-dot ${aiKey()?'':'off'}"></span>${aiKey()?'AI examiner connected':'AI examiner not connected'}</div>${setupAI()}<a class="sideLink" href="${p.qp}" target="_blank">Open original question paper ↗</a></aside></div>`}
function getAnswer(q,key){if(q.type==='mcq'){let e=document.querySelector('input[name=mcq]:checked');return e?e.value:''}return document.querySelector('#ans')?.value.trim()||''}
function has(a,keys){a=a.toLowerCase().replace(/[–—]/g,'-');return keys.some(k=>a.includes(k))}
function mark(){let p=state.paper,q=qs[state.qi],key=p.id+'-'+state.qi,a=getAnswer(q,key);if(!a)return alert('Write or select an answer first.');state.answers[key]=a;let score=0,details=[];
 if(q.type==='mcq'){score=a===q.correct?1:0;details=[{ok:score===1,text:score?'Correct answer.':`The credited answer is ${q.correct}.`}];}
 else if(q.groups){let best=[];for(const g of q.groups){let d=g.map(x=>({ok:has(a,x[1]),text:x[0]}));if(d.filter(x=>x.ok).length>best.filter(x=>x.ok).length)best=d}score=best.filter(x=>x.ok).length;details=best;}
 else if(q.alts){let ok=has(a,q.keys);score=ok?1:0;details=[{ok,text:ok?'Creditable answer.':`Credit requires one of: ${q.alts.join('; ')}.`}];}
 else {details=q.scheme.map(x=>({ok:has(a,x[1]),text:x[0]}));score=details.filter(x=>x.ok).length;if(q.cap)score=Math.min(score,q.cap);score=Math.min(score,q.marks)}
 state.results[key]={score,details,answer:a};render();}
function resultHTML(r,q){let full=r.score===q.marks;return `<div class="result"><div class="resultHead"><div><span class="tiny">MARK</span><div class="bigScore">${r.score}<small>/${q.marks}</small></div></div><div class="verdict ${full?'full':''}">${full?'Full marks':'Improve and retry'}</div></div><h3>Mark-scheme breakdown</h3>${r.details.map(d=>`<div class="point ${d.ok?'hit':'miss'}"><span>${d.ok?'✓':'×'}</span><div>${d.text}</div></div>`).join('')}${r.ai?`<div class="ai-feedback"><div class="ai-title">✦ AI examiner feedback</div><div class="ai-body"><h4>Feedback</h4><p>${esc(r.feedback)}</p><h4>Improved answer</h4><p>${esc(r.improved)}</p></div></div>`:''}${q.note?`<div class="guidance"><b>Examiner guidance</b><br>${q.note}</div>`:''}<button class="retry" onclick="document.querySelector('#ans')?.focus()">Edit answer & retry</button></div>`}
function clearAns(){let p=state.paper,key=p.id+'-'+state.qi;delete state.answers[key];delete state.results[key];render()}
render();
